### ISSUE TITLE
Create sa and add self-provisioner role

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/toolchain-operator#2]
We need one Service Account to provision required namespace and used by tenant service. Add `self-provisioner` cluster role to it.

@pbergene, I believe this `sa` needs to create `resourcequotas` and `limitranges` when used in tenant service. We also need `rolebindingrestictions` as well. Do we need anything other than that? any specific resources and it's required action(create/update/delete/get)?

cc @alexeykazakov

**Comment by dipak-pawar** [comment]
In OSD cluster support we don't need to apply any limitranges/quota restrictions. So I think only creation of `service account` and assigning `self-provisioner` roles to create namespace/projects is enough.

**Comment by pbergene** [comment]
This has already been set up along with @alexeykazakov.  What part of the work is this and where is it happening? I wouldn't exclude limitranges or resourcequotas completely, they are still a way to manage capacity - to prevent rouge projects without limits or request from killing cluster nodes.

Also note that there is currently no model for doing a lot of common operator patterns on osd (crds, clusterroles, clusterrolebindings etc).

**Comment by alexeykazakov** [comment]
@pbergene this issue is not about setting up some particular cluster (like dsaas) but about adding functionality to our OSIO operator, so, it will create a service account (to be used by OSIO) when installed on the cluster.

**Comment by pbergene** [comment]
Ah, I see. The SA setup proposed is basically what we've been testing with on dsaas, so that should be sufficient.
