### ISSUE TITLE
GetServiceAccount not checked for error that isn't a not-found error.

### ISSUE THREAD

**Issue by kwk** [fabric8-services/toolchain-operator#29]
The `err` returned from `GetServiceAccount` is not checked for an error that is not a not-found error.

https://github.com/fabric8-services/toolchain-operator/blob/3797fbd4e7641fdfa364461c773fa45690586dfe/pkg/controller/toolchainenabler/toolchainenabler_controller.go#L154

Is it only checked for a not-found  error.

https://github.com/fabric8-services/toolchain-operator/blob/3797fbd4e7641fdfa364461c773fa45690586dfe/pkg/controller/toolchainenabler/toolchainenabler_controller.go#L155

**Comment by dipak-pawar** [comment]
Good find @kwk
