### ISSUE TITLE
Add proper rolebinding to the cluster SA

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/toolchain-operator#33]
Here is the Role we should bind to our devtools-sre SA - https://github.com/openshift/online/blob/master/ansible/roles/oso_dsaas_admin_osio/files/dsaas-cluster-admin.json

**Comment by dipak-pawar** [comment]
@alexeykazakov, I can't see self-provisioning capabilities(ability to create new-project) available after applying this `dsaas-cluster-admin` clusterrole. Does this mean we are creating two clusterrolebinding, one with role `dsaas-cluster-admin`  and one with role `self-provisioner` binding to SA `devtools-sre`?

If yes, then does SD team do this manually?

cc @pbergene

**Comment by pbergene** [comment]
The dsaas cluster admin role is what is used on the osio tenant clusters and would not be in use on OSD, but any think lacking from dedicated-admin would need to be accounted for.

Also the dsaas-cluster admin is applied to a *user* which come with self-provisioner out of the box. Serviceaccounts however, do not.

**Comment by dipak-pawar** [comment]
thank you @pbergene.

@alexeykazakov From my understanding this `dsaas-cluster-admin` cluster role won't be exists in OSD cluster, our operator will create it and there is no need to to run this ansible playbook by sre

**Comment by alexeykazakov** [comment]
@dipak-pawar correct. The idea is to use our operator to configure the cluster. So +1 to add the role creation and binding to our operator.
