### ISSUE TITLE
Figure out how to get the routing suffix(app-dns)

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/toolchain-operator#4]
Our internal services need routing suffix for openshift cluster, where user application routes are created.

We need this information to be stored in cluster information.

@pbergene, I am not sure how do we get wildcard dns configured on the OpenShift master for installing OpenShift. Do you know if we have any way for this?

cc @alexeykazakov

**Comment by pbergene** [comment]
there is an internal dns resolver already, we will not be running anything else.  What exactly are you trying to accomplish, we will not be setting any custom records on the master dns.

**Comment by dipak-pawar** [comment]
@pbergene, For OSIO, we need `app-dns` to be stored as part of cluster information so that required services can use it when required to create a route for OSIO end user applications.

While enabling/installing `OSIO` on any OSD cluster, we would like to find this cluster DNS.

**Comment by pbergene** [comment]
Right, I understand the context now.  We've looked into this previously and it was not exposed on the cluster, hence why it is stored explicitly. 

The options that come to mind would be getting this from the router pod secrets / cert (although I'm not sure there would be access to this) or perhaps querying UHC, which presumably has this information.  Else there is the workaround of creating a route and parsing that definition, but that's not very clean.

**Comment by pbergene** [comment]
@jhernand Would know if this is something you could query, but I'm not sure how this would all come together.  What data would you input to the query?

**Comment by pbergene** [comment]
This whole flow and integration would need to be documented up. cc @kbsingh

**Comment by jhernand** [comment]
@pbergene @dipak-pawar In UHC we don't store that information, at least not currently.

The reference documentation of the UHC API is here: https://api.openshift.com

**Comment by dipak-pawar** [comment]
@jhernand, thank you, for the UHC API documentation link
